services:
  nodejs-app:
    build: ./app
    container_name: mi-nodejs-app
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./app:/usr/src/app

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
    driver: local